#!/bin/sh

xrandr --dpi 120
export AWT_TOOLKIT=MToolkit
export XDG_SESSION_TYPE=x11
export GTK_THEME=Adwaita:dark
export QT_STYLE_OVERRIDE=Adwaita-Dark
[ -f $HOME/.config/bspwm/bspwmenv ] && source "$HOME/.config/bspwm/bspwmenv"
[ -f $HOME/.config/X11/Xresources ] && xrdb $HOME/.config/X11/Xresources
killall sxhkd
killall fullscreen_single
while pgrep -u "$(whoami)" -x sxhkd; do sleep 1; done
sxhkd &
start_compositor &
autostart
ln -s $HOME/bin/notificate.sh.bak $HOME/bin/notificate.sh

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
[ -f "$HOME/.cache/.nomonitorsetup" ] || monitorsetup

# won't work if not all connected monitors are active as active != connected
monitors=$(xrandr --listactivemonitors | tail -n +2 | awk '{print $4}')
for monitor in $monitors; do
	bspc monitor "$monitor" --reset-desktops "${monitor}_1" "${monitor}_2" "${monitor}_3" "${monitor}_4" "${monitor}_5" "${monitor}_6" "${monitor}_7" "${monitor}_8" "${monitor}_9"
done

# Remove old monitors in bspwm, which aren't active anymore (may happen when restarting bspwm)
for monitor in $(bspc query --monitors --names); do
	if ! echo "$monitors" | grep -q "$monitor"; then

		for desktop in $(bspc query -D -m "${monitor}" ); do
			for node in $(bspc query --nodes --desktop "${desktop}"); do
				bspc node "$node" --to-desktop focused
			done
			bspc desktop $desktop --remove
		done
		bspc monitor "$monitor" --remove
	fi
done


moveDesktopsToMonitors.sh &

setWallpaper &
setStatusbar &
setNotifications &

"${configsdir}/scripts/startPolkitAgent" &
systemctl --user restart fullscreend.service

bspc config border_width        2
rm -f "$XDG_CACHE_HOME/window_gap"
if xrandr | grep primary -q; then
	_primary=$(xrandr | grep primary)
else
	_primary=$(xrandr | grep "$(bspc query -M --names | head -n 1)")
fi
[ "$(printf '%s' "$_primary" | sed -e 's/primary //g' -e 's/+/ /g' -e 's/x/ /g' | awk -e '{ print $3 }')" -ge 2560 ] && _gapsize=50 || _gapsize=8
bspc config window_gap	$_gapsize

bspc config split_ratio          0.52

bspc config click_to_focus any

# bspc rule -a polybar layer=below
bspc rule -a GLava layer=below sticky=on state=fullscreen
bspc rule -a Gimp state=floating follow=on
bspc rule -a Steam state=floating
bspc rule -a Spotipyne state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled
bspc rule -a Godot state=floating
# xmodmap "${configsdir}/CapsLockEscapeSwapper"
