#!/bin/bash

node_of_interest=$1
if [ "$(bspc node $node_of_interest.fullscreen)" ]; then 
	echo "fullscreen"
elif [ "$(bspc node $node_of_interest.pseudo_tiled)" ]; then
	echo "pseudo_tiled"
elif [ "$(bspc node $node_of_interest.floating)" ]; then 
	echo "floating"
else
	echo "tiled"
fi
