#!/bin/sh

start_if_absent() {
pgrep $1 || $1 &
}

if true; then
start_if_absent telegram-desktop
start_if_absent signal-desktop
sh -c 'pgrep discord-canary || while discord-canary; do :; done' &
fi >/dev/null 2>&1
