#!/bin/zsh

WALLPAPER_SYMLINK="$(xdg-user-dir PICTURES)/wallpaper"
WALLPAPERS_DIR="$(xdg-user-dir WALLPAPER)"

if ! readlink -f "${WALLPAPERS_DIR}" >/dev/null 2>&1; then
	WALLPAPERS_DIR="${HOME}/configs/wallpapers/"
fi

delete_current_wallpaper() {
	abs_path=$(readlink -f "$WALLPAPER_SYMLINK")
	rm -f "$abs_path"
	return 0
}

[ "$1" = "delete" ] || [ "$1" = "d" ] || [ "$1" = "del" ] && delete_current_wallpaper
[ -d "$(readlink -f ${@: -1} 2>/dev/null)" ] && WALLPAPERS_DIR="${@: -1}"

which identify >/dev/null || exit 1

while NEW_WALLPAPER=$(find $WALLPAPERS_DIR -mindepth 1  | shuf -n 1 ); ! identify $NEW_WALLPAPER >/dev/null 2>&1 ; do
	echo $NEW_WALLPAPER;
done
ln -sf "$(readlink -f $NEW_WALLPAPER)" "$WALLPAPER_SYMLINK"
wal -c
[ "$1" = "pywal" ] && wal -n -i "$WALLPAPER_SYMLINK" || wal --theme $HOME/configs/nord-theme.json
# which oomox-cli >/dev/null && oomox-cli "$HOME/.cache/wal/colors-oomox" -o wal >/dev/null &
feh --no-fehbg --bg-fill "${WALLPAPER_SYMLINK}"
. "${XDG_CACHE_HOME}/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
which update-discord-wal >/dev/null && update-discord-wal
